### ISSUE TITLE
DRM Platform.

### ISSUE THREAD

**Issue by colesnicov** [raylib-extras/raylib_multi_window_experimental#2]
Please, before submitting a new issue verify and check:

 - [ ] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

Hello. According to this https://github.com/raysan5/raylib/issues/3946#issuecomment-2092824678 issue, it won't work on a DRM platform.

**Comment by JeffM2501** [comment]
DRM doesn't support multiple windows. so... that makes sense.
